name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SSH & Deploy on EC2
      uses: appleboy/ssh-action@master
      with:
        host: 54.89.166.57              
        username: ubuntu                   
        key: ${{ secrets.EC2_SSH_KEY }}    
        script: |
          cd /home/ubuntu/2-tier-web-app
          git pull origin main
          docker-compose down
          docker-compose up -d --build
